# -*- coding: utf-8 -*-
"""Project 1 Cross-Market Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_1QtGUcrKu561Zm9E3wuyxU6LHuncnA

Cryptocurrency
"""

import requests
import time

CMA_Records = []
url = "https://api.coingecko.com/api/v3/coins/markets"

for page in range(1, 6):
    params = {
        "vs_currency": "inr",
        "order": "market_cap_desc",
        "per_page": 250,
        "page": page,
        "sparkline": "false"
    }
    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()
        CMA_Records.extend(data)

Crypo_Records=[]
for i in CMA_Records:
 Crypo_Records.append(dict(id=i['id'],symbol=i['symbol'],name =i['name'], current_price=i['current_price'], market_cap =i['market_cap'], market_cap_rank=i['market_cap_rank'], total_volume=i['total_volume'], circulating_supply=i['circulating_supply'], total_supply=i['total_supply'], ath=i['ath'], atl=i['atl'], date=i['last_updated'].split("T")[0] if i.get('last_updated') else None))

import pandas as pd

Cryto_coins_df=pd.DataFrame(Crypo_Records)

Cryto_coins_df.to_csv("Cryto_coins_df.csv",index = False)

Cryto_coins_df.csv= pd.read_csv("Cryto_coins_df.csv")

Cryto_coins_df

"""Top 5 Coins – Historical Prices"""

import requests
import pandas as pd
import time

coin_ids = ["bitcoin","ethereum","tether","binancecoin","ripple"]

top_historical = []

for coin in coin_ids:

    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart?vs_currency=usd&days=365"

    while True:
        response = requests.get(url)

        if response.status_code == 200:
            coin_data = response.json()

            for price_data in coin_data["prices"]:
                date = pd.to_datetime(price_data[0], unit="ms").date()
                price = price_data[1]

                top_historical.append({
                    "coin_id": coin,
                    "date": date,
                    "price_inr": price
                })

            print(f"{coin} data collected")
            break

        elif response.status_code == 429:
            print("Rate limit hit. Waiting 60 seconds...")
            time.sleep(60)

        else:
            print("API Error:", response.status_code)
            break

    time.sleep(5)
Top_5_Historical_df = pd.DataFrame(top_historical)

Top_5_Historical_df.to_csv("Top_5_Historical_df.csv",index = False)

import pandas as pd

Top_5_Historical_df.csv= pd.read_csv("Top_5_Historical_df.csv")

Top_5_Historical_df

"""Oil Prices"""

import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df

oil_filtered = oil_df[
    (oil_df["Date"] >= "2020-01-01") &
    (oil_df["Date"] <= "2026-01-31")
]

oil_filtered

oil_filtered.to_csv("oil_prices.csv",index = False)

import pandas as pd

oil_df = pd.read_csv("oil_prices.csv")

oil_df

"""Stock Prices (Yahoo Finance API)

"""

pip install yfinance pandas

import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2025-09-30"

Stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")

Stocks_df=Stocks_df.dropna()

Stocks_df=Stocks_df.reset_index()
Stocks_df.head()

import yfinance as yf
import pandas as pd

# tickers
tickers = ["^GSPC", "^IXIC", "^NSEI"]

# date range
start_date = "2020-01-01"
end_date = "2025-09-30"

# download data
Stocks_df = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    group_by="ticker"
)
Stocks_df=Stocks_df.dropna()
Stocks_df.head()

stocks_list = []

for ticker in tickers:
    df = Stocks_df[ticker].reset_index()
    df["ticker"] = ticker
    stocks_list.append(df)

stocks_all = pd.concat(stocks_list)

stocks_all.head()

stocks_all.to_csv("stocks_all.csv",index = False)

import pandas as pd

stocks_all_df = pd.read_csv("stocks_all.csv")

stocks_all_df

len(stocks_all)

import sqlite3
connection=sqlite3.connect("Market.db")
cursor=connection.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS Cryptocurrencies (
    id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18,6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(20,6),
    total_supply DECIMAL(20,6),
    ath DECIMAL(18,6),
    atl DECIMAL(18,6),
    last_updated DATE
);
''')
print("✅ Table created successfully!")

cursor.execute("SELECT name FROM sqlite_master where type = 'table'")
print(cursor.fetchall())

cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table'")
for row in cursor.fetchall():
    print(row)

Cryto_coins_df.csv= pd.read_csv("Cryto_coins_df.csv")

Cryto_coins_df.head()

Cryto_coins_df.to_sql(
    "Cryptocurrencies",
    connection,
    if_exists="replace",   # replaces table
    index=False
)

print("✅ Data replaced successfully")

connection.commit()

import pandas as pd

pd.read_sql("SELECT * FROM Cryptocurrencies LIMIT 5", connection)

cursor.execute("""
CREATE TABLE IF NOT EXISTS  Crypto_prices (coin_id VARCHAR(50),
    date DATE,
    price_inr DECIMAL(18,6),
    PRIMARY KEY (coin_id, date),
    FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id)
)
""")

connection.commit()

print("✅ Crypto_Prices table created successfully")

cursor.execute("SELECT name FROM sqlite_master where type = 'table'")
print(cursor.fetchall())

cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table'")
for row in cursor.fetchall():
    print(row)

import pandas as pd

Top_5_Historical_df.csv= pd.read_csv("Top_5_Historical_df.csv")

Top_5_Historical_df

Top_5_Historical_df.to_sql(
    "Crypto_prices",
    connection,
    if_exists="replace",   # replaces table
    index=False
)

print("✅ Data replaced successfully")

connection.commit()

import pandas as pd

pd.read_sql("SELECT * FROM Crypto_prices LIMIT 5", connection)

import sqlite3

conn = sqlite3.connect("Market.db")
cursor = conn.cursor()

# Drop the table
cursor.execute("DROP TABLE IF EXISTS oil_prices")



# Recreate the table
cursor.execute("""
CREATE TABLE Oil_prices (
    date DATE PRIMARY KEY,
    price_inr DECIMAL(18,6)
)
""")


conn.commit()


print("oil_prices table recreated successfully")

cursor.execute("SELECT name FROM sqlite_master where type = 'table'")
print(cursor.fetchall())

cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table'")
for row in cursor.fetchall():
    print(row)

import pandas as pd

oil_df = pd.read_csv("oil_prices.csv")

oil_df

oil_df.to_sql(
    "Oil_prices",
    connection,
    if_exists="replace",   # replaces table
    index=False
)

connection.commit()

print("✅ Data replaced successfully")

import pandas as pd

pd.read_sql("SELECT * FROM Oil_prices LIMIT 5", connection)

import sqlite3

conn = sqlite3.connect("Market.db")
cursor = conn.cursor()

# Drop the table
cursor.execute("DROP TABLE IF EXISTS Stock_prices")





cursor.execute("""
CREATE TABLE Stock_prices (
    date DATE,
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    volume BIGINT,
    ticker VARCHAR(20),
    PRIMARY KEY (date, ticker)
)
""")

connection.commit()

print("✅ Stock_prices table created successfully")

cursor.execute("SELECT name FROM sqlite_master where type = 'table'")
print(cursor.fetchall())

cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table'")
for row in cursor.fetchall():
    print(row)

import pandas as pd

stocks_all_df = pd.read_csv("stocks_all.csv")

stocks_all_df

stocks_all_df.to_sql(
    "Stock_prices",
    connection,
    if_exists="replace",   # replaces table
    index=False
)

connection.commit()

print("✅ Data replaced successfully")

import pandas as pd

pd.read_sql("SELECT * FROM Stock_prices LIMIT 5", connection)

"""SQL Queries (crypto_prices )

1.Find the top 3 cryptocurrencies by market cap.
"""

Crp_query1 = """
SELECT id, symbol, name, market_cap
FROM Cryptocurrencies
ORDER BY market_cap DESC
LIMIT 3
"""

cursor.execute(Crp_query1)
result = cursor.fetchall()

for row in result:
    print(row)

"""2.List all coins where circulating supply exceeds 90% of total supply."""

Crp_query2 = """
SELECT id, symbol, name,circulating_supply,total_supply
FROM Cryptocurrencies
WHERE circulating_supply >= 0.9 * total_supply
"""


cursor.execute(Crp_query2)
result = cursor.fetchall()

for row in result:
    print(row)

"""3.Get coins that are within 10% of their all-time-high (ATH).

"""

Crp_query3 = """
SELECT id, symbol, name,current_price,ath
FROM Cryptocurrencies
WHERE current_price >= 0.9 * ath
"""

cursor.execute(Crp_query3)
result = cursor.fetchall()

for row in result:
    print(row)

"""4.Find the average market cap rank of coins with volume above $1B."""

Crp_query4 = """SELECT AVG(market_cap_rank) AS avg_market_cap_rank
FROM Cryptocurrencies
WHERE total_volume > 1000000000
"""



cursor.execute(Crp_query4)
result = cursor.fetchall()

for row in result:
    print(row)

"""5.Get the most recently updated coin."""

Crp_query5 = """
SELECT id, symbol, name, date
FROM Cryptocurrencies
ORDER BY date DESC
LIMIT 1
"""


cursor.execute(Crp_query5)
result = cursor.fetchall()

for row in result:
    print(row)

"""crypto_prices (daily prices of top coins)

"""

#1.Find the highest daily price of Bitcoin in the last 365 days.

CP_query1 = """
SELECT date, price_inr
FROM Crypto_Prices
WHERE coin_id = 'bitcoin'
ORDER BY price_inr DESC
LIMIT 1;
"""

cursor.execute(CP_query1)
result = cursor.fetchall()
for row in result:
    print(row)

"""2.Caculate the average daily price of Ethereum in the past 1 year."""

CP_query2 = """
SELECT AVG(price_inr) AS avg_price
FROM Crypto_Prices
WHERE coin_id = 'ethereum'

"""

cursor.execute(CP_query2)
result = cursor.fetchall()
for row in result:
    print(row)

"""3.Show the daily price trend of Bitcoin in March 2025. (or change the month and year according you your data)

"""

import pandas as pd
CP_query3 = """
SELECT date, price_inr
FROM Crypto_Prices
WHERE coin_id = 'bitcoin'
AND date BETWEEN '2025-03-01' AND '2025-03-31'
ORDER BY date;

"""

Bitcoin_dp_df = pd.read_sql(CP_query3, connection)
print(Bitcoin_dp_df)

"""4.Find the coin with the highest average price over 1 year.

"""

import pandas as pd
CP_query4 = """
SELECT coin_id, AVG(price_inr) AS avg_price
FROM Crypto_Prices
GROUP BY coin_id
ORDER BY avg_price DESC
LIMIT 1
"""

cursor.execute(CP_query4)
result = cursor.fetchall()
for row in result:
    print(row)

"""5.Get the % change in Bitcoin’s price between Mar 2025-July 2025 and Aug 2025-Jan 2026.

"""

import pandas as pd
CP_query5_2025 = """
SELECT price_inr FROM Crypto_Prices
WHERE coin_id='bitcoin'
AND date BETWEEN '2025-03-01' AND '2025-07-31'
ORDER BY date LIMIT 1
"""

cursor.execute(CP_query5_2025)
result1 = cursor.fetchall()

print(result1)




CP_query5_2026 = """
SELECT price_inr FROM Crypto_Prices
WHERE coin_id='bitcoin'
AND date BETWEEN '2025-08-01' AND '2026-01-31'
ORDER BY date LIMIT 1
"""

cursor.execute(CP_query5_2026)
result2 = cursor.fetchone()
print(result2)

price_2025 = float(result1[0][0])   # first element of the first row
price_2026 = float(result2[0])      # first element of the tuple from fetchone()

# Calculate percentage change
percent_change = ((price_2026 - price_2025) / price_2025) * 100

print("Bitcoin % change:", round(percent_change,2), "%")

"""oil_prices

1.Find the highest oil price in the last 5 years.
"""

import pandas as pd
OP_query1 = """
SELECT date, price
FROM Oil_prices
WHERE date BETWEEN '2021-01-01' AND '2026-01-31'
ORDER BY price DESC
LIMIT 1
"""
cursor.execute(OP_query1)
result = cursor.fetchall()
for row in result:
    print(row)

"""2.Get the average oil price per year.

"""

import sqlite3
import pandas as pd

OP_query2 = """
SELECT strftime('%Y', date) AS year,AVG(price) AS avg_price
FROM Oil_prices
GROUP BY year
ORDER BY year;
"""

avg_oil_per_year = pd.read_sql(OP_query2, connection)
print(avg_oil_per_year)

"""3.Show oil prices during COVID crash (March–April 2020)."""

import pandas as pd
OP_query3 = """
SELECT date, price
FROM Oil_prices
WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
ORDER BY date;
"""

COVID_crash = pd.read_sql(OP_query3, connection)
print(COVID_crash)

"""4.Find the lowest price of oil in the last 10 years."""

import pandas as pd
OP_query4 = """
SELECT date, price
FROM Oil_prices
WHERE date BETWEEN '2016-01-01' AND '2026-01-31'
ORDER BY price ASC
LIMIT 1
"""
cursor.execute(OP_query4)
result = cursor.fetchall()
for row in result:
    print(row)

"""5.Calculate the volatility of oil prices (max-min difference per year)."""

import pandas as pd
OP_query5 = """
SELECT strftime('%Y', date) AS year,MAX(price) - MIN(price) AS volatility
FROM Oil_prices
GROUP BY year
ORDER BY year;
"""

volatility_oil = pd.read_sql(OP_query5, connection)
print(volatility_oil)

"""stock_prices

1.Get all stock prices for a given ticker
"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")
tickers = ["^GSPC", "^IXIC", "^NSEI"]
tickers_str = ",".join([f"'{t}'" for t in tickers])

SP_query1 =f"""
SELECT *
FROM Stock_prices
WHERE ticker IN ({tickers_str})
ORDER BY date;
"""

stock_prices_df = pd.read_sql(SP_query1, connection)
print("📊 Stock Prices DataFrame:")
print(stock_prices_df)

connection.close()

pivot_df = stock_prices_df.pivot(index='Date', columns='ticker', values='Close')

print("\n  Pivot Table (Closing Prices):")
print(pivot_df)

"""2.Find the highest closing price for NASDAQ (^IXIC)"""

SP_query2 ="""
SELECT Date, Close
FROM Stock_prices
WHERE ticker = '^IXIC'
ORDER BY Close DESC
LIMIT 1;
"""
cursor.execute(SP_query2)
result = cursor.fetchall()
for row in result:
    print(f'NASDAQ (IXIC) highest Close price{row}')

"""3.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")
SP_query3 = """
SELECT date, high, low, (high - low) AS daily_range
FROM Stock_prices
WHERE ticker = '^GSPC'
ORDER BY daily_range DESC
LIMIT 5;
"""

top5_ranges = pd.read_sql(SP_query3, connection)
print("Top 5 Days with Highest Price Difference for GSPC:")
print(top5_ranges)

connection.close()

"""4.Get monthly average closing price for each ticker"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")

SP_query4 = """
SELECT
    ticker,
    strftime('%Y-%m', date) AS year_month,
    AVG(close) AS avg_close
FROM Stock_prices
GROUP BY ticker, year_month
ORDER BY ticker, year_month;
"""

monthly_avg_df = pd.read_sql(SP_query4, connection)
print(monthly_avg_df)

connection.close()

"""5.Get average trading volume of NSEI in 2024"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")
SP_query5 ="""
SELECT Date, AVG(Volume) AS Avg_Volume
FROM Stock_prices
WHERE ticker = '^NSEI'
AND date BETWEEN '2024-01-01' AND '2024-12-31';
"""
avg_volume_df = pd.read_sql(SP_query5, connection)
print("Average NSEI trading volume in 2024:", int(avg_volume_df['Avg_Volume'][0]))


connection.close()

"""🔗 Join Queries (Cross-Market Analysis)

1.Compare Bitcoin vs Oil average price in 2025.
"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")

Join_query1 = """
SELECT 'Bitcoin' AS asset, AVG(price_inr) AS avg_price
FROM Crypto_Prices
WHERE coin_id = 'bitcoin' AND strftime('%Y', date) = '2025'

UNION ALL

SELECT 'Oil' AS asset, AVG(price) AS avg_price
FROM Oil_prices
WHERE strftime('%Y', date) = '2025';
"""

comparison_df = pd.read_sql(Join_query1, connection)

print("Bitcoin vs Oil average price in 2025:")
print(comparison_df)

connection.close()

"""2.Check if Bitcoin moves with S&P 500 (correlation idea).

"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query2 = """
SELECT
    cp.date,
    cp.price_inr AS Bitcoin_price,
    Sp.Close AS sp500_price
FROM crypto_prices cp
LEFT JOIN Stock_Prices  sp
ON cp.date = sp.date
WHERE cp.coin_id = 'bitcoin' AND sp.ticker = '^GSPC'
ORDER BY cp.date
"""

B_df = pd.read_sql(Join_query2, connection)
connection.close()

# Calculate correlation

correlation = B_df['Bitcoin_price'].corr(B_df['sp500_price'])

print("Bitcoin vs S&P 500 correlation:")
print(correlation)

"""3.Compare Ethereum and NASDAQ daily prices for 2025."""

import sqlite3
import pandas as pd
connection = sqlite3.connect("Market.db")

Join_query3= """
SELECT 'Ethereum' AS asset, price_inr AS price,date
FROM Crypto_Prices
WHERE coin_id = 'ethereum' AND date BETWEEN '2025-01-01' AND '2025-12-31'

UNION ALL

SELECT 'NASDAQ' AS asset, Close AS price,date
FROM Stock_prices
WHERE ticker = '^IXIC';
"""

Comparison_df1 = pd.read_sql(Join_query3, connection)

print("Ethereum vs IXIC Daily price in 2025:")
print(Comparison_df1)

connection.close()

"""4.Find days when oil price spiked and compare with Bitcoin price change.

"""

import sqlite3
import pandas as pd

connection = sqlite3.connect("Market.db")

Join_query4= """
WITH Oil_Returns AS (
    SELECT
        Date,
        Price,
        LAG(Price) OVER (ORDER BY Date) AS prev_price,
        ((Price - LAG(Price) OVER (ORDER BY Date)) / LAG(Price) OVER (ORDER BY Date)) * 100 AS oil_return
    FROM Oil_prices
    WHERE Date BETWEEN '2025-01-01' AND '2025-12-31'
)
SELECT
    oil.Date,
    oil.Price AS oil_price,
    oil.oil_return,
    crp.price_inr AS bitcoin_price
FROM Oil_Returns oil
LEFT JOIN Crypto_Prices crp ON oil.Date=crp.date
AND crp.coin_id = 'bitcoin'

WHERE oil.oil_return > 5
ORDER BY oil.Date;
"""

oil_bitcoin_df = pd.read_sql(Join_query4, connection)


connection.close()


print("Oil spike days with Bitcoin prices:")
print(oil_bitcoin_df)

"""5.Compare top 3 coins daily price trend vs Nifty (^NSEI).

"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query5 = """
SELECT date, 'bitcoin' AS asset, price_inr AS price
FROM Crypto_Prices
WHERE coin_id = 'bitcoin' AND date BETWEEN '2025-01-01' AND '2025-12-31'

UNION ALL

SELECT date, 'ethereum' AS asset, price_inr AS price
FROM Crypto_Prices
WHERE coin_id = 'ethereum' AND date BETWEEN '2025-01-01' AND '2025-12-31'

UNION ALL

SELECT date, 'tether' AS asset, price_inr AS price
FROM Crypto_Prices
WHERE coin_id = 'tether' AND date BETWEEN '2025-01-01' AND '2025-12-31'

UNION ALL

SELECT date, '^NSEI' AS asset, Close AS price
FROM Stock_Prices
WHERE ticker = '^NSEI' AND date BETWEEN '2025-01-01' AND '2025-12-31'
"""

trend_df = pd.read_sql(Join_query5, connection)

connection.close()

print("Top 3 coins daily prices vs Nifty (^NSEI) in 2025:")
print(trend_df.head(30))

Comparison_pivot = trend_df.pivot(index='date', columns='asset', values='price').reset_index()

print("Top 3 coins daily prices vs Nifty (^NSEI) in 2025:")
print(Comparison_pivot)

"""6.Compare stock prices (^GSPC) with crude oil prices on the same dates"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query6 = """
SELECT
    sp.date,
    sp.Close AS sp500_price,
    op.Price AS oil_price
FROM stock_prices sp
LEFT JOIN oil_prices op
ON sp.date = op.date
WHERE sp.ticker = '^GSPC'
ORDER BY sp.date
"""
crud_oil_df = pd.read_sql(Join_query6, connection)

connection.close()

print("Compare S&P 500 and Crude Oil Prices:")
print(crud_oil_df.head(10))

"""7.Correlate Bitcoin closing price with crude oil closing price (same date)

"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query7 = """
SELECT
    cp.date,
    cp.price_inr AS Bitcoin_closing_price,
    op.Price AS oil_closing_price
FROM crypto_prices cp
LEFT JOIN oil_prices op
ON cp.date = op.date
WHERE cp.coin_id = 'bitcoin'
ORDER BY cp.date
"""
Bitcoin_CP_df = pd.read_sql(Join_query7, connection)

connection.close()

print("Compare Bitcon closing price and Crude Oil Closing Prices:")
print(Bitcoin_CP_df.head(10))

"""8.Compare NASDAQ (^IXIC) with Ethereum price trends"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query8 = """
SELECT
    sp.date,
    sp.Close AS Nasag_price,
    cp.price_inr AS Ethereum_price
FROM stock_prices sp
LEFT JOIN crypto_prices cp
ON sp.date = cp.date
WHERE sp.ticker = '^IXIC' AND cp.coin_id = 'ethereum'
ORDER BY sp.date
"""

Trends_CP_df = pd.read_sql(Join_query8, connection)


connection.close()

print("Compare NASDAG Price and Ethereum Prices:")
print(Bitcoin_CP_df.head(10))

"""Join top 3 crypto coins with stock indices for 2025

"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query9 = """
SELECT date,coin_id AS asset, price_inr AS price
FROM Crypto_Prices
WHERE coin_id IN ('bitcoin','ethereum','tether')
AND date BETWEEN '2025-01-01' AND '2025-12-31'

UNION ALL

SELECT date,ticker AS asset, Close AS price
FROM Stock_Prices
WHERE ticker IN ('^NSEI','^IXIC','^GSPC')
AND date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY date,asset
"""

Crp_Stock_df = pd.read_sql(Join_query9, connection)

connection.close()

print("Top 3 coins prices vs Stock in 2025:")
print(Crp_Stock_df.head(10))

Comparison_pivot1= Crp_Stock_df.pivot(index='date', columns='asset', values='price').reset_index()

print("Top 3 coins prices vs Stock in 2025:")
print(Comparison_pivot1)

"""10.Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

"""

import sqlite3
import pandas as pd


connection = sqlite3.connect("Market.db")


Join_query10 = """
SELECT
    cp.date,
    cp.price_inr AS Bitcoin_price,
    sp.Close AS Stock_price,
    op.Price AS Oil_price
FROM crypto_prices  cp
LEFT JOIN stock_prices sp
ON cp.date = sp.date AND
sp.ticker = '^GSPC'

LEFT JOIN oil_prices op
ON cp.date= op.date

WHERE cp.coin_id = 'bitcoin'
ORDER BY cp.date
"""

Multi_Join_df = pd.read_sql(Join_query10, connection)


connection.close()

print("Multi-join: stock prices, oil prices, and Bitcoin prices :")
print(Multi_Join_df.head(10))

!pip install streamlit

!pip install pyngrok

import streamlit as st
import sqlite3
import pandas as pd

st.title("💰🛢️📈 Cross-Market Analysis Dashboard")

connection = sqlite3.connect("Market.db")

# ----------------------
# Bitcoin vs Oil
# ----------------------

query1 = """
SELECT
cp.date,
cp.price_inr AS Bitcoin,
op.Price AS Oil
FROM crypto_prices cp
LEFT JOIN oil_prices op
ON cp.date = op.date
WHERE cp.coin_id='bitcoin'
ORDER BY cp.date
"""

df = pd.read_sql(query1, connection)

st.subheader("Bitcoin vs Oil Prices")

st.dataframe(df)

st.line_chart(df.set_index("date"))

connection.close()

from google.colab import files
files.download('Market.db')